// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Non-null assertion because Prisma requires a string URL here; ensure DATABASE_URL is set at runtime.
    url: process.env["DATABASE_URL"]!,
  },
});
